apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: seata-deployment
  labels:
    name: seata-deployment
spec:
  template:
    metadata:
      labels:
        app: seata
    spec:
      containers:
        - name: fescar
          imagePullPolicy: IfNotPresent
          image: {{ .Values.server.fescar.image.registry }}{{ .Values.server.fescar.image.name }}:{{ .Values.server.fescar.image.tag }}
          ports:
            - containerPort: {{ .Values.server.fescar.image.port }}
        - name: nacos
          imagePullPolicy: IfNotPresent
          image: {{ .Values.server.nacos.image.name }}:{{ .Values.server.nacos.image.tag }}
          ports:
            - containerPort: {{ .Values.server.nacos.image.port }}
          env:
            - name: MODE
              value: "standalone"
        - name: mysql
          imagePullPolicy: IfNotPresent
          image: {{ .Values.server.mysql.image.name }}:{{ .Values.server.mysql.image.tag }}
          ports:
            - containerPort: {{ .Values.server.mysql.image.port }}
          env:
            - name: MYSQL_DATABASE
              value: "db_gts_fescar"
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
