apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    name: seata-service
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.server.mysql.image.port }}
    name: "mysql"
    targetPort: {{ .Values.server.mysql.image.port }}
    protocol: TCP
  selector:
    app: seata
---
apiVersion: v1
kind: Service
metadata:
  name: nacos
  labels:
    name: seata-service
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.server.nacos.image.port }}
    name: "nacos"
    targetPort: {{ .Values.server.nacos.image.port }}
    protocol: TCP
  selector:
    app: seata
---
apiVersion: v1
kind: Service
metadata:
  name: fescar
  labels:
    name: seata-service
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.server.fescar.image.port }}
    name: "feacar"
    targetPort: {{ .Values.server.fescar.image.port }}
    protocol: TCP
  selector:
    app: seata
---
