apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    name: seata-service
spec:
  type: ClusterIP
  ports:
  - port: 3306
    name: "mysql"
    targetPort: 3306
    protocol: TCP
  selector:
    app: seata
---
apiVersion: v1
kind: Service
metadata:
  name: nacos
  labels:
    name: seata-service
spec:
  type: ClusterIP
  ports:
  - port: 8848
    name: "nacos"
    targetPort: 8848
    protocol: TCP
  selector:
    app: seata
---
apiVersion: v1
kind: Service
metadata:
  name: fescar
  labels:
    name: seata-service
spec:
  type: ClusterIP
  ports:
  - port: 8091
    name: "feacar"
    targetPort: 8091
    protocol: TCP
  selector:
    app: seata
---
