apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.client.business.name }}-service
  labels:
    name: {{ .Values.client.business.name }}-service
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.client.business.image.port }}
    name: "seata-business"
    targetPort: {{ .Values.client.business.image.port }}
    protocol: TCP
  selector:
    app: {{ .Values.client.business.name }}
