apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.client.account.name }}-service
  labels:
    name: {{ .Values.client.account.name }}-service
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.client.account.image.port }}
    name: "account"
    targetPort: {{ .Values.client.account.image.port }}
    protocol: TCP
  - port: {{ .Values.client.storage.image.port }}
    name: "storage"
    targetPort: {{ .Values.client.storage.image.port }}
    protocol: TCP
  selector:
    app: {{ .Values.client.account.name }}
