apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.client.order.name }}-deployment
  labels:
    name: {{ .Values.client.order.name }}-deployment
spec:
  template:
    metadata:
      labels:
        app: {{ .Values.client.order.name }}
    spec:
      containers:
        - name: {{ .Values.client.order.name }}
          imagePullPolicy: IfNotPresent
          image: {{ .Values.client.order.image.registry }}{{ .Values.client.order.image.name }}:{{ .Values.client.order.image.tag }}
          ports:
            - containerPort: {{ .Values.client.order.image.port }}
