apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.client.order.name }}-service
  labels:
    name: {{ .Values.client.order.name }}-service
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.client.order.image.port }}
    name: "order-service"
    targetPort: {{ .Values.client.order.image.port }}
    protocol: TCP
  selector:
    app: {{ .Values.client.order.name }}
