apiVersion: v1
kind: Service
metadata:
  name: seata-order-service
  labels:
    name: seata-order-service
spec:
  type: ClusterIP
  ports:
  - port: 8101
    name: "order-service"
    targetPort: 8101
    protocol: TCP
  selector:
    app: seata-order
