server:
    fescar:
        image:
            registry:
            name: "seata"
            tag: "0.9.0"
            port: 8091
    nacos:
        image:
            name: "nacos/nacos-server"
            tag: "latest"
            port: 8848
    mysql:
        image:
            name: "mysql"
            tag: "5.6"   
            port: 3306 